apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-new-headless
  namespace: logging
spec:
  clusterIP: None
  selector:
    app: elasticsearch-master-new
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport

